In [11]:
data = read.table("data.csv", 
                  header = TRUE,
                  sep=",",
                  stringsAsFactors=TRUE)
head(data, n=4)
summary(data)

  ClaimID                              PatientID
1 10944daf-f7d5-4e1d-8216-72ffa609fe41 8552381d-7960-4f64-b190-b20b8ada00a1
2 fcbebb25-fc24-4c0f-a966-749edcf83fb1 327f43ad-e3bd-4473-a9ed-46483a0a156f
3 9e9983e7-9ea7-45f5-84d8-ce49ccd8a4a1 6f3acdf7-73aa-4afa-9c2e-b25b27bdb5b0
4 a06273ed-44bb-452b-bbad-8618de080494 5d58e183-701e-406c-a8c6-5b73cac5e912
  ProviderID                           ClaimAmount ClaimDate  DiagnosisCode
1 4a4cb19c-4863-41cf-84b0-c2b21aace988 3807.95     2024-06-07 yy006
2 422e02dd-c1fd-43dd-8af4-0c3523f997b1 9512.07     2023-05-30 tD052
3 f7733b3f-0980-47b5-a7a0-ee390869355b 7346.74     2022-09-27 zx832
4 f7a04581-de96-44ee-b773-8adac02baa59 6026.72     2023-06-25 kr421
  ProcedureCode PatientAge PatientGender ProviderSpecialty ClaimStatus
1 hd662         16         M             Cardiology        Pending
2 mH831         27         M             Pediatrics        Approved
3 dg637         40         F             Cardiology        Pending
4 kG326         65         M             Neurology         Pending
  PatientIncome PatientMaritalStatus PatientEmploymentStatus ProviderLocation
1  90279.43     Married              Retired                 Jameshaven
2 130448.02     Single               Student                 Beltrantown
3  82417.54     Divorced             Employed                West Charlesport
4  68516.96     Widowed              Student                 West Aprilhaven
  ClaimType ClaimSubmissionMethod
1 Routine   Paper
2 Routine   Online
3 Emergency Online
4 Routine   Phone

                                 ClaimID
 002b68ab-2074-434f-bfdd-763ef3cb583e:   1
 0033ce58-e5af-4573-a9bc-1c7e639f3ec1:   1
 00395890-1b73-48f6-b24c-fedd0a45a080:   1
 005d7e2a-ff14-4c8f-a4b9-877d92543aae:   1
 0068e41f-4897-4a08-a3af-7d690fe22e5a:   1
 006f5f7f-0360-4afc-8590-482a98d76495:   1
 (Other)                             :4494
                                PatientID
 000f4454-0d12-4a00-8cbd-943e3730f99b:   1
 001ed9ce-670b-478d-80c7-44b3fe8a8ef6:   1
 00236546-ccac-4607-aef0-f22518e0e459:   1
 002e8db4-4731-48c5-8b65-241f0f20b726:   1
 003662ef-f5b8-4920-8873-45ea0d926b0c:   1
 0036f180-dd7b-463c-9da7-6d228870887a:   1
 (Other)                             :4494
                                ProviderID    ClaimAmount          ClaimDate
 001333d4-0aba-4805-87b5-49f4c88d69ca:   1   Min.   : 100.1   2023-06-20:  15
 002882c5-9ea4-4158-bef7-2a046c6f7ecb:   1   1st Qu.:2509.1   2023-07-24:  14
 0038f9e8-145e-44df-bd43-4e26ff327e58:   1   Median :5053.8   2022-09-24:  13
 004d07a1-c7ae-485f-a2ca-feb99c30f176:   1   Mean   :5014.2   2022-10-22:  13
 00698dd9-fb4c-4365-a82b-8cf0c67482e9:   1   3rd Qu.:7462.5   2023-09-26:  13
 006c8459-efb3-4a9b-ba66-b288c7b937a8:   1   Max.   :9997.2   2023-11-21:  13
 (Other)                             :4494                    (Other)   :4419
 DiagnosisCode  ProcedureCode    PatientAge    PatientGender
 aE034  :   2   zW098  :   3   Min.   : 0.00   F:2282
 iR323  :   2   tY099  :   2   1st Qu.:25.00   M:2218
 OC742  :   2   tZ954  :   2   Median :50.50
 pa477  :   2   zE112  :   2   Mean   :49.84
 TK486  :   2   aA026  :   1   3rd Qu.:75.00
 Aa122  :   1   aA273  :   1   Max.   :99.00
 (Other):4489   (Other):4489
        ProviderSpecialty   ClaimStatus   PatientIncome    PatientMaritalStatus
 Cardiology      :907     Approved:1522   Min.   : 20007   Divorced:1101
 General Practice:880     Denied  :1512   1st Qu.: 52792   Married :1181
 Neurology       :865     Pending :1466   Median : 84061   Single  :1091
 Orthopedics     :893                     Mean   : 84384   Widowed :1127
 Pediatrics      :955                     3rd Qu.:115768
                                          Max.   :149958

 PatientEmploymentStatus         ProviderLocation      ClaimType
 Employed  :1188         North Michael   :   8    Emergency :1071
 Retired   :1061         Port Jennifer   :   6    Inpatient :1128
 Student   :1110         South Michael   :   6    Outpatient:1152
 Unemployed:1141         East Christopher:   5    Routine   :1149
                         Lake Angela     :   5
                         Lake James      :   5
                         (Other)         :4465
 ClaimSubmissionMethod
 Online:1461
 Paper :1544
 Phone :1495

In [12]:
new_data = data[,c(5, 4)]
new_data = na.omit(unique(new_data))

head(new_data, n=4)

  ClaimDate  ClaimAmount
1 2024-06-07 3807.95
2 2023-05-30 9512.07
3 2022-09-27 7346.74
4 2023-06-25 6026.72

In [13]:
write.csv(new_data,"new_data.csv")