---

# First Data:

https://data.mendeley.com/datasets/992mh7dk9y/2

---

In [9]:
data = read.table("test.csv", 
                  header = TRUE,
                  sep=",",
                  stringsAsFactors=TRUE)
head(data, n=4)

  months_as_customer age policy_number policy_bind_date policy_state policy_csl
1 328                48  521585        2014-10-17       OH           250/500
2 228                42  342868        2006-06-27       IN           250/500
3 134                29  687698        2000-09-06       OH           100/300
4 256                41  227811        1990-05-25       IL           250/500
  policy_deductable policy_annual_premium umbrella_limit insured_zip ⋯
1 1000              1406.91                     0        466132      ⋯
2 2000              1197.22               5000000        468176      ⋯
3 2000              1413.14               5000000        430632      ⋯
4 2000              1415.74               6000000        608117      ⋯
  police_report_available total_claim_amount injury_claim property_claim
1 YES                     71610              6510         13020
2 ?                        5070               780           780
3 NO                      34650              7700          3850
4 NO                      63400              6340          6340
  vehicle_claim auto_make auto_model auto_year fraud_reported X_c39
1 52080         Saab      92x        2004      Y              NA
2  3510         Mercedes  E400       2007      Y              NA
3 23100         Dodge     RAM        2007      N              NA
4 50720         Chevrolet Tahoe      2014      Y              NA

In [4]:
names(data)

 [1] "months_as_customer"          "age"
 [3] "policy_number"               "policy_bind_date"
 [5] "policy_state"                "policy_csl"
 [7] "policy_deductable"           "policy_annual_premium"
 [9] "umbrella_limit"              "insured_zip"
[11] "insured_sex"                 "insured_education_level"
[13] "insured_occupation"          "insured_hobbies"
[15] "insured_relationship"        "capital.gains"
[17] "capital.loss"                "incident_date"
[19] "incident_type"               "collision_type"
[21] "incident_severity"           "authorities_contacted"
[23] "incident_state"              "incident_city"
[25] "incident_location"           "incident_hour_of_the_day"
[27] "number_of_vehicles_involved" "property_damage"
[29] "bodily_injuries"             "witnesses"
[31] "police_report_available"     "total_claim_amount"
[33] "injury_claim"                "property_claim"
[35] "vehicle_claim"               "auto_make"
[37] "auto_model"                  "auto_year"
[39] "fraud_reported"              "X_c39"

In [8]:
new_data = data[,c(18, 32)]
head(new_data, n=4)

  incident_date total_claim_amount
1 2015-01-25    71610
2 2015-01-21     5070
3 2015-02-22    34650
4 2015-01-10    63400

In [10]:
write.csv(new_data,"new_data.csv")

In [11]:
summary(new_data$incident_date)

2015-01-01 2015-01-02 2015-01-03 2015-01-04 2015-01-05 2015-01-06 2015-01-07
        19         11         18         12          7         17         25
2015-01-08 2015-01-09 2015-01-10 2015-01-11 2015-01-12 2015-01-13 2015-01-14
        22         17         24          9         19         21         19
2015-01-15 2015-01-16 2015-01-17 2015-01-18 2015-01-19 2015-01-20 2015-01-21
        15         16         15         18         23         18         19
2015-01-22 2015-01-23 2015-01-24 2015-01-25 2015-01-26 2015-01-27 2015-01-28
        14         13         24         10         11         13         15
2015-01-29 2015-01-30 2015-01-31 2015-02-01 2015-02-02 2015-02-03 2015-02-04
        11         21         20         18         28         13         24
2015-02-05 2015-02-06 2015-02-07 2015-02-08 2015-02-09 2015-02-10 2015-02-11
        16         20         10         17         13         10         10
2015-02-12 2015-02-13 2015-02-14 2015-02-15 2015-02-16 2015-02-17 2015-02-18
        20         16         18         16         16         26         15
2015-02-19 2015-02-20 2015-02-21 2015-02-22 2015-02-23 2015-02-24 2015-02-25
        10         14         19         20         19         17         18
2015-02-26 2015-02-27 2015-02-28 2015-03-01
        17         14         18         12

--- 
# second dataset

https://huggingface.co/datasets/designfailure/Insurance-car_claims/blob/main/insurance_data%20%7BAnalyst%7D%20.xlsx

---

In [13]:
data = read.table("insu_data.csv", 
                  header = TRUE,
                  sep=";",
                  stringsAsFactors=TRUE)
head(data, n=4)

  customer_ID first_name last_name birth_date gender
1 CUST10000   Edin       Klemenčič 1936-07-20 M
2 CUST10001   Albert     Potočnik  1975-09-12 M
3 CUST10002   Dragan     Košir     1941-06-30 M
4 CUST10003   Bernard    Bevc      1999-05-13 M
  address                           region     registration_date
1 Livada 18, 9600 Litija            Kranj      2018-01-19
2 Šmarna gora 4b, 2654 Litija       Ptuj       2025-04-19
3 Polje, cesta XXXIV 4b, 7816 Žalec Velenje    2018-08-28
4 Černivčeva ulica 341, 1647 Koper  Novo mesto 2019-06-06

In [14]:
summary(data)

    customer_ID      first_name     last_name         birth_date   gender
 CUST10000:   1   Saša    :  47   Likar  :  79   1998-09-14:   5   F:5000
 CUST10001:   1   Radovan :  45   Rožman :  73   1937-08-06:   4   M:5000
 CUST10002:   1   Joško   :  43   Cerar  :  72   1939-06-18:   4
 CUST10003:   1   Sabina  :  43   Medved :  72   1940-09-05:   4
 CUST10004:   1   Mirjam  :  42   Pavlič :  72   1947-10-14:   4
 CUST10005:   1   Antonija:  41   Kalan  :  71   1953-12-29:   4
 (Other)  :9994   (Other) :9739   (Other):9561   (Other)   :9975
                                     address            region
 Abramova ulica 1c, 9258 Ribnica         :   1   Novo mesto:1311
 Abramova ulica 2a, 4185 Dravograd       :   1   Maribor   :1264
 Abramova ulica 2c, 9225 Ilirska Bistrica:   1   Celje     :1257
 Abramova ulica 37, 3619 Litija          :   1   Velenje   :1250
 Abramova ulica 4b, 1116 Vipavski Križ   :   1   Ptuj      :1236
 Abramova ulica 5, 2316 Tolmin           :   1   Koper     :1233
 (Other)                                 :9994   (Other)   :2449
  registration_date
 2025-01-07:   9
 2015-12-20:   8
 2016-03-02:   8
 2016-03-21:   8
 2016-05-10:   8
 2017-06-14:   8
 (Other)   :9951

In [15]:
summary(new_data)

    incident_date total_claim_amount
 2015-02-02: 28   Min.   :   100
 2015-02-17: 26   1st Qu.: 41813
 2015-01-07: 25   Median : 58055
 2015-01-10: 24   Mean   : 52762
 2015-01-24: 24   3rd Qu.: 70593
 2015-02-04: 24   Max.   :114920
 (Other)   :849

In [17]:
data = read.table("heatl_data.csv", 
                  header = TRUE,
                  sep=",",
                  stringsAsFactors=TRUE)
head(data, n=4)

  ClaimID                              PatientID
1 10944daf-f7d5-4e1d-8216-72ffa609fe41 8552381d-7960-4f64-b190-b20b8ada00a1
2 fcbebb25-fc24-4c0f-a966-749edcf83fb1 327f43ad-e3bd-4473-a9ed-46483a0a156f
3 9e9983e7-9ea7-45f5-84d8-ce49ccd8a4a1 6f3acdf7-73aa-4afa-9c2e-b25b27bdb5b0
4 a06273ed-44bb-452b-bbad-8618de080494 5d58e183-701e-406c-a8c6-5b73cac5e912
  ProviderID                           ClaimAmount ClaimDate  DiagnosisCode
1 4a4cb19c-4863-41cf-84b0-c2b21aace988 3807.95     2024-06-07 yy006
2 422e02dd-c1fd-43dd-8af4-0c3523f997b1 9512.07     2023-05-30 tD052
3 f7733b3f-0980-47b5-a7a0-ee390869355b 7346.74     2022-09-27 zx832
4 f7a04581-de96-44ee-b773-8adac02baa59 6026.72     2023-06-25 kr421
  ProcedureCode PatientAge PatientGender ProviderSpecialty ClaimStatus
1 hd662         16         M             Cardiology        Pending
2 mH831         27         M             Pediatrics        Approved
3 dg637         40         F             Cardiology        Pending
4 kG326         65         M             Neurology         Pending
  PatientIncome PatientMaritalStatus PatientEmploymentStatus ProviderLocation
1  90279.43     Married              Retired                 Jameshaven
2 130448.02     Single               Student                 Beltrantown
3  82417.54     Divorced             Employed                West Charlesport
4  68516.96     Widowed              Student                 West Aprilhaven
  ClaimType ClaimSubmissionMethod
1 Routine   Paper
2 Routine   Online
3 Emergency Online
4 Routine   Phone

In [18]:
summary(data)

                                 ClaimID
 002b68ab-2074-434f-bfdd-763ef3cb583e:   1
 0033ce58-e5af-4573-a9bc-1c7e639f3ec1:   1
 00395890-1b73-48f6-b24c-fedd0a45a080:   1
 005d7e2a-ff14-4c8f-a4b9-877d92543aae:   1
 0068e41f-4897-4a08-a3af-7d690fe22e5a:   1
 006f5f7f-0360-4afc-8590-482a98d76495:   1
 (Other)                             :4494
                                PatientID
 000f4454-0d12-4a00-8cbd-943e3730f99b:   1
 001ed9ce-670b-478d-80c7-44b3fe8a8ef6:   1
 00236546-ccac-4607-aef0-f22518e0e459:   1
 002e8db4-4731-48c5-8b65-241f0f20b726:   1
 003662ef-f5b8-4920-8873-45ea0d926b0c:   1
 0036f180-dd7b-463c-9da7-6d228870887a:   1
 (Other)                             :4494
                                ProviderID    ClaimAmount          ClaimDate
 001333d4-0aba-4805-87b5-49f4c88d69ca:   1   Min.   : 100.1   2023-06-20:  15
 002882c5-9ea4-4158-bef7-2a046c6f7ecb:   1   1st Qu.:2509.1   2023-07-24:  14
 0038f9e8-145e-44df-bd43-4e26ff327e58:   1   Median :5053.8   2022-09-24:  13
 004d07a1-c7ae-485f-a2ca-feb99c30f176:   1   Mean   :5014.2   2022-10-22:  13
 00698dd9-fb4c-4365-a82b-8cf0c67482e9:   1   3rd Qu.:7462.5   2023-09-26:  13
 006c8459-efb3-4a9b-ba66-b288c7b937a8:   1   Max.   :9997.2   2023-11-21:  13
 (Other)                             :4494                    (Other)   :4419
 DiagnosisCode  ProcedureCode    PatientAge    PatientGender
 aE034  :   2   zW098  :   3   Min.   : 0.00   F:2282
 iR323  :   2   tY099  :   2   1st Qu.:25.00   M:2218
 OC742  :   2   tZ954  :   2   Median :50.50
 pa477  :   2   zE112  :   2   Mean   :49.84
 TK486  :   2   aA026  :   1   3rd Qu.:75.00
 Aa122  :   1   aA273  :   1   Max.   :99.00
 (Other):4489   (Other):4489
        ProviderSpecialty   ClaimStatus   PatientIncome    PatientMaritalStatus
 Cardiology      :907     Approved:1522   Min.   : 20007   Divorced:1101
 General Practice:880     Denied  :1512   1st Qu.: 52792   Married :1181
 Neurology       :865     Pending :1466   Median : 84061   Single  :1091
 Orthopedics     :893                     Mean   : 84384   Widowed :1127
 Pediatrics      :955                     3rd Qu.:115768
                                          Max.   :149958

 PatientEmploymentStatus         ProviderLocation      ClaimType
 Employed  :1188         North Michael   :   8    Emergency :1071
 Retired   :1061         Port Jennifer   :   6    Inpatient :1128
 Student   :1110         South Michael   :   6    Outpatient:1152
 Unemployed:1141         East Christopher:   5    Routine   :1149
                         Lake Angela     :   5
                         Lake James      :   5
                         (Other)         :4465
 ClaimSubmissionMethod
 Online:1461
 Paper :1544
 Phone :1495